# Generated by Django 5.2.11 on 2026-03-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('global', 'Global'), ('custom', 'Custom')], default='global', help_text='Optional logical grouping for this form (no FK).', max_length=50)),
                ('target_id', models.PositiveIntegerField(default=0, help_text='Optional numeric identifier, meaning depends on target_type.')),
                ('is_published', models.BooleanField(default=False)),
                ('allow_anonymous', models.BooleanField(default=False)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedback Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('rating', 'Rating'), ('yes_no', 'Yes/No')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'verbose_name_plural': 'Feedback Questions',
                'ordering': ['form_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=255)),
                ('option_value', models.CharField(help_text='Machine-readable value submitted when this option is selected.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedback.feedbackquestion')),
            ],
            options={
                'verbose_name_plural': 'Feedback Question Options',
                'ordering': ['question_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('draft', 'Draft')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='feedback.feedbackform')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedback Submissions',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_number', models.FloatField(blank=True, null=True)),
                ('answer_bool', models.BooleanField(blank=True, null=True)),
                ('answer_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbacksubmission')),
            ],
            options={
                'verbose_name_plural': 'Feedback Answers',
            },
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['created_by', 'created_at'], name='feedback_fe_created_4d7282_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['target_type', 'target_id'], name='feedback_fe_target__cf4846_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['is_published', 'start_at', 'end_at'], name='feedback_fe_is_publ_45b586_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackquestion',
            index=models.Index(fields=['form', 'sort_order'], name='feedback_fe_form_id_0060f1_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackquestionoption',
            index=models.Index(fields=['question', 'sort_order'], name='feedback_fe_questio_030411_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['form', 'student'], name='feedback_fe_form_id_1e6be8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['status'], name='feedback_fe_status_d80031_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackanswer',
            index=models.Index(fields=['submission', 'question'], name='feedback_fe_submiss_1fb86a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackanswer',
            unique_together={('submission', 'question')},
        ),
    ]
