# Generated by Django 5.2.11 on 2026-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='allow_edit_after_submit',
            field=models.BooleanField(default=False),
        ),
    ]
