# Generated by Django 5.0.6 on 2025-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
