# Generated by Django 5.0.6 on 2025-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_managment", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
