# Generated by Django 5.2.7 on 2025-11-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0005_user_bio_user_title_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Instructor biography', max_length=500, null=True),
        ),
    ]
