# Generated by Django 5.2.7 on 2025-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
