# Generated by Django 5.2.7 on 2025-11-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0007_role_slug_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
