# Generated by Django 5.2.8 on 2025-11-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0008_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='user_managm_user_id_9c5b83_idx',
            old_name='user_manag_user_id_b8f15b_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='user_managm_expires_581e3f_idx',
            old_name='user_manag_expires_74ca64_idx',
        ),
    ]
