# Generated by Django 5.2.7 on 2025-11-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0008_alter_role_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='slug',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
