# Generated by Django 5.0.6 on 2025-09-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_conversation_courseannouncement_courseqa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlelesson',
            options={'verbose_name_plural': 'ArticleLesson'},
        ),
        migrations.AlterModelOptions(
            name='assignmentlesson',
            options={'verbose_name_plural': 'AssignmentLesson'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Certificate'},
        ),
        migrations.AlterModelOptions(
            name='checkpointquizresponse',
            options={'ordering': ['-responded_at'], 'verbose_name_plural': 'Check Point Response'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at'], 'verbose_name_plural': 'Conversation '},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseannouncement',
            options={'ordering': ['-is_pinned', '-published_at', '-created_at'], 'verbose_name_plural': 'Course Announcement'},
        ),
        migrations.AlterModelOptions(
            name='coursebadge',
            options={'verbose_name_plural': 'LessonCourseBadge'},
        ),
        migrations.AlterModelOptions(
            name='courseqa',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name_plural': 'CourseQA'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Course Rating'},
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['order', 'created_at'], 'verbose_name_plural': 'Course Resources'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name_plural': 'Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'created_at'], 'verbose_name_plural': 'Lesson'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson__order'], 'verbose_name_plural': 'LessonProgress'},
        ),
        migrations.AlterModelOptions(
            name='lessonresource',
            options={'verbose_name_plural': 'LessonResource'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Level'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at'], 'verbose_name_plural': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ['order'], 'verbose_name_plural': 'QuizAnswer'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-completed_at'], 'verbose_name_plural': 'QuizAttempt'},
        ),
        migrations.AlterModelOptions(
            name='quizconfiguration',
            options={'verbose_name_plural': 'QuizConfiguration'},
        ),
        migrations.AlterModelOptions(
            name='quizlesson',
            options={'verbose_name_plural': 'QuizLesson'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order', 'created_at'], 'verbose_name_plural': 'QuizQuestion'},
        ),
        migrations.AlterModelOptions(
            name='resourceprogress',
            options={'verbose_name_plural': 'ResourceProgress'},
        ),
        migrations.AlterModelOptions(
            name='videocheckpointquiz',
            options={'ordering': ['timestamp_seconds'], 'verbose_name_plural': 'Video Check point Quiz'},
        ),
        migrations.AlterModelOptions(
            name='videocheckpointresponse',
            options={'ordering': ['-responded_at'], 'verbose_name_plural': 'Video Checkpoint Responses'},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'verbose_name_plural': 'VideoLesson'},
        ),
        migrations.AddField(
            model_name='course',
            name='issue_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.course'),
        ),
    ]
