# Generated by Django 5.0.6 on 2025-09-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_course_alter_lesson_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_order_per_course',
        ),
    ]
