# Generated by Django 5.0.6 on 2025-10-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_unique_lesson_order_per_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='course',
            name='flagged_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='flagged_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_flagged',
        ),
    ]
