# Generated by Django 5.0.6 on 2025-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_flag_reason_remove_course_flagged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlesson',
            name='submission_types',
            field=models.JSONField(blank=True, default=list, help_text='List of submission types, e.g. ["file", "text"]'),
        ),
    ]
