# Generated by Django 4.2.25 on 2025-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_flag_reason_remove_course_flagged_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursebadge',
            options={'verbose_name_plural': 'LessonCourseBadges'},
        ),
        migrations.AlterField(
            model_name='coursebadge',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('rising_star', 'Rising Star'), ('top_rated', 'Top Rated'), ('trending_now', 'Trending Now'), ('masterclass', 'Masterclass'), ('student_favorite', 'Student Favorite'), ('impact_award', 'Impact Award'), ('legendary', 'Legendary Course')], default='rising_star', max_length=30, null=True),
        ),
    ]
