# Generated by Django 5.0.6 on 2025-11-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_assignmentlesson_submission_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlesson',
            name='tasks',
            field=models.JSONField(blank=True, default=list, help_text='List of tasks for the assignment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
