# Generated by Django 4.2.25 on 2025-10-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(blank=True, default=list, help_text='List of course objectives or goals.')),
                ('what_you_will_learn', models.JSONField(blank=True, default=list, help_text='List of bullet points about what users will learn.')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of course requirements or prerequisites.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='courses.course')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
