# Generated by Django 5.2.7 on 2025-11-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignmentlesson_tasks_enrollment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.CharField(default='', help_text="e.g., '2h 30m'", max_length=50),
        ),
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('objective', models.JSONField(blank=True, default=list)),
                ('what_you_will_learn', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='courses.course')),
            ],
        ),
    ]
