# Generated by Django 4.2.25 on 2025-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseoverview_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of course objectives or goals.', null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of course requirements or prerequisites.', null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet points about what users will learn.', null=True),
        ),
    ]
