# Generated by Django 5.2.7 on 2025-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointquizresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
