# Generated by Django 4.2.25 on 2025-10-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursefaq_course_objectives_course_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The frequently asked question', max_length=500)),
                ('answer', models.TextField(help_text='The answer to the frequently asked question', max_length=1000)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in FAQ list')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Course FAQ',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CourseFAQ',
        ),
        migrations.AddField(
            model_name='course',
            name='course_faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.faq'),
        ),
    ]
