# Generated by Django 5.2.7 on 2025-11-04 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def dedupe_lesson_order_per_module(apps, schema_editor):
    """
    Ensure Lesson.order is unique within each module before adding the
    unique constraint (module, order). We keep existing relative ordering
    by sorting by (order, id) and then renumbering sequentially starting at 1.
    Lessons without a module are ignored because the constraint is conditional
    on module IS NOT NULL.
    """
    Lesson = apps.get_model('courses', 'Lesson')

    # Distinct module ids where module is not null
    module_ids = (
        Lesson.objects.exclude(module__isnull=True)
        .values_list('module_id', flat=True)
        .distinct()
    )

    for module_id in module_ids:
        lessons = list(
            Lesson.objects.filter(module_id=module_id).order_by('order', 'id')
        )
        # Renumber sequentially to eliminate duplicates and invalid values
        for idx, lesson in enumerate(lessons, start=1):
            lesson.order = idx
        if lessons:
            Lesson.objects.bulk_update(lessons, ['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_checkpointquizresponse_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='assessment_answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Assessment Answers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_points', models.FloatField(default=0.0)),
                ('earned_points', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Assessment Attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('fill-blank', 'Fill in Blank'), ('short-answer', 'Short Answer')], default='multiple-choice', max_length=20)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='assessment_questions/')),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blanks', models.JSONField(blank=True, default=list, help_text='List of correct answers for blanks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assessment Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='For fill-in-blank or short answer questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Assessment Responses',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('submission_url', models.URLField(blank=True)),
                ('github_repo', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalCourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Passing score percentage')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum attempts allowed')),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Time limit in minutes')),
                ('randomize_questions', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Final Course Assessments',
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_attachments/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lesson Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Module Progress',
                'ordering': ['module__order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='For fill-in-blank or short answer questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Quiz Responses',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order', 'created_at'], 'verbose_name_plural': 'Lesson'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id', 'order'], 'verbose_name_plural': 'Modules'},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='completed',
            new_name='is_unlocked',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='articlelesson',
            name='attachments',
        ),
        migrations.AddField(
            model_name='articlelesson',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articlelesson',
            name='title',
            field=models.CharField(default='Untitled Lesson', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_enrolled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='lesson_file_attachments/'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlelesson',
            name='estimated_read_time',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated based on word count'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='courses_enr_student_774ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_completed'], name='courses_enr_is_comp_5bc92c_idx'),
        ),
        # Data migration to fix duplicate lesson order values per module
        migrations.RunPython(dedupe_lesson_order_per_module, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('module', 'order'), name='unique_lesson_order_per_module'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_responses', to='courses.assessmentanswer'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='courses.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalcourseassessment',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.finalcourseassessment'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.finalcourseassessment'),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.module'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_responses', to='courses.quizanswer'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='courses.quizquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('enrollment', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
