# Generated by Django 5.2.7 on 2025-11-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_assessmentanswer_assessmentattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.AddField(
            model_name='module',
            name='number_of_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.module'),
        ),
    ]
