# Generated by Django 5.2.7 on 2025-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_category_count_module_number_of_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverview',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='what_you_will_learn',
        ),
        migrations.AddField(
            model_name='course',
            name='objective',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
