# Generated by Django 5.2.7 on 2025-11-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_courseoverview_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='number_of_lessons',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
