# Generated by Django 5.2.7 on 2025-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_module_number_of_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.CharField(blank=True, default='', help_text="e.g., '2h 30m'", max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
