# Generated by Django 5.2.7 on 2025-11-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelesson',
            name='estimated_read_time',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Auto-calculated based on word count'),
        ),
    ]
