# Generated by Django 5.2.7 on 2025-11-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_articlelesson_estimated_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelesson',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='article_attachments/'),
        ),
    ]
