# Generated by Django 5.2.7 on 2025-11-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_articlelesson_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelesson',
            name='attachments_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
