# Generated by Django 5.2.7 on 2025-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_articlelesson_attachments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('link', 'External Link'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], default='pdf', max_length=50),
        ),
    ]
