# Generated by Django 5.2.7 on 2025-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_lessonresource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], default='pdf', max_length=50),
        ),
    ]
