# Generated by Django 5.2.7 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_lessonresource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='chapters',
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
