# Generated by Django 5.2.7 on 2025-11-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_videolesson_chapters_alter_videolesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='attachments',
        ),
        migrations.CreateModel(
            name='VideoLessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='video_lesson_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.videolesson')),
            ],
        ),
    ]
