# Generated by Django 5.2.7 on 2025-11-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_videolesson_attachments_videolessonattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelesson',
            name='attachments',
        ),
        migrations.CreateModel(
            name='ArticleLessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article_lesson_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.articlelesson')),
            ],
        ),
    ]
