# Generated by Django 5.2.7 on 2025-11-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_articlelessonattachment_article_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelesson',
            name='external_links',
        ),
    ]
