# Generated by Django 5.2.7 on 2025-11-06 06:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_articlelesson_external_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-completed_at', '-started_at'], 'verbose_name_plural': 'QuizAttempt'},
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='drag_item_images',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='drop_zone_images',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='earned_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 6, 9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for drag & drop onto image', null=True, upload_to='quiz_questions/drag_drop_images/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='categorization_categories',
            field=models.JSONField(blank=True, default=list, help_text="Categories: [{'id': 1, 'name': 'Mammals', 'color': '#ff0000'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='categorization_correct_mappings',
            field=models.JSONField(blank=True, default=dict, help_text="Correct mappings: {'item_id': 'category_id', ...}"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='categorization_items',
            field=models.JSONField(blank=True, default=list, help_text="Items to categorize: [{'id': 1, 'text': 'Dog', 'image': 'url'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='cloze_answers',
            field=models.JSONField(blank=True, default=list, help_text='List of correct answers for each blank in order'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='cloze_options',
            field=models.JSONField(blank=True, default=list, help_text='List of draggable options for cloze questions'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='cloze_text',
            field=models.TextField(blank=True, help_text="Text with blanks marked (e.g., 'The largest planet is ___.')"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_correct_mappings',
            field=models.JSONField(blank=True, default=dict, help_text="Correct mappings: {'drag_item_id': 'drop_zone_id', ...}"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_drag_items',
            field=models.JSONField(blank=True, default=list, help_text="List of draggable items: [{'id': 1, 'text': 'Nucleus', 'image': 'url'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_drop_zones',
            field=models.JSONField(blank=True, default=list, help_text="List of drop zones with coordinates: [{'id': 1, 'x': 100, 'y': 200, 'label': 'Nucleus'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='matching_correct_pairs',
            field=models.JSONField(blank=True, default=list, help_text="Correct pairs: [{'left_id': 1, 'right_id': 2}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='matching_left_items',
            field=models.JSONField(blank=True, default=list, help_text="Left side items: [{'id': 1, 'text': 'France', 'image': 'url'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='matching_right_items',
            field=models.JSONField(blank=True, default=list, help_text="Right side items: [{'id': 1, 'text': 'Paris', 'image': 'url'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='sequencing_correct_order',
            field=models.JSONField(blank=True, default=list, help_text='Correct order as list of item IDs: [1, 3, 2, 4]'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='sequencing_items',
            field=models.JSONField(blank=True, default=list, help_text="Items to sequence: [{'id': 1, 'text': 'Step 1', 'image': 'url'}, ...]"),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='drag_drop_response',
            field=models.JSONField(blank=True, default=dict, help_text='For drag & drop questions: stores mappings, sequences, or categorizations'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quizconfiguration',
            name='grading_policy',
            field=models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Attempt'), ('average', 'Average Score'), ('first', 'First Attempt')], default='highest', help_text='How to calculate final score from multiple attempts', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizconfiguration',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AlterField(
            model_name='quizconfiguration',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Minimum percentage required to pass (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quizconfiguration',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='Whether to show questions in random order'),
        ),
        migrations.AlterField(
            model_name='quizconfiguration',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Display correct answers after submission'),
        ),
        migrations.AlterField(
            model_name='quizconfiguration',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes. Specify the time limit for the quiz.'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='blanks',
            field=models.JSONField(blank=True, default=list, help_text='List of correct answers for blanks. For multiple blanks, use list of strings.'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='drag_drop_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Correct drag-drop mappings (deprecated)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='drag_items',
            field=models.JSONField(blank=True, default=list, help_text='List of draggable items (deprecated)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='drop_zones',
            field=models.JSONField(blank=True, default=list, help_text='List of drop zones (deprecated)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points the question carries (e.g., 5 marks, 3 marks)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('fill-blank', 'Fill in Blank'), ('drag-drop-text', 'Drag & Drop onto Text'), ('drag-drop-image', 'Drag & Drop onto Image'), ('drag-drop-matching', 'Drag & Drop Matching'), ('drag-drop-sequencing', 'Drag & Drop Sequencing'), ('drag-drop-categorization', 'Drag & Drop Categorization'), ('short-answer', 'Short Answer')], default='multiple-choice', max_length=30),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'lesson', '-completed_at'], name='courses_qui_student_422495_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['attempt', 'question'], name='courses_qui_attempt_d9e0cf_idx'),
        ),
    ]
