# Generated by Django 5.2.7 on 2025-11-07 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlesson',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quizlesson'),
        ),
        migrations.AlterField(
            model_name='quizlesson',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('fill-blank', 'Fill in Blank'), ('drag-drop-text', 'Drag & Drop onto Text'), ('drag-drop-image', 'Drag & Drop onto Image'), ('drag-drop-matching', 'Drag & Drop Matching'), ('drag-drop-sequencing', 'Drag & Drop Sequencing'), ('drag-drop-categorization', 'Drag & Drop Categorization'), ('short-answer', 'Short Answer')], default='multiple-choice', max_length=50),
        ),
    ]
