# Generated by Django 5.2.7 on 2025-11-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_quizlesson_questions_quizquestion_quiz_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='blanks',
            field=models.JSONField(blank=True, default=list, help_text='List of correct answers for blanks. For multiple blanks, use list of strings.', null=True),
        ),
    ]
