# Generated by Django 5.2.7 on 2025-11-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_quizquestion_blanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='blanks',
            field=models.JSONField(blank=True, default=list, help_text='List of correct answers for blanks. For multiple blanks, use list of strings.'),
        ),
    ]
