# Generated by Django 5.2.8 on 2025-11-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_quizquestion_blanks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at'], 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at'], 'verbose_name_plural': 'Messages'},
        ),
    ]
