# Generated by Django 5.2.8 on 2025-11-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_conversation_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlesson',
            name='grading_policy',
            field=models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Attempt'), ('average', 'Average Score'), ('first', 'First Attempt')], default='highest', max_length=20),
        ),
    ]
