# Generated by Django 5.2.8 on 2025-11-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_quizlesson_grading_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz_lesson',
        ),
    ]
