# Generated by Django 5.2.8 on 2025-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_remove_quizquestion_quiz_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='categorization_categories',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='categorization_correct_mappings',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='categorization_items',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='cloze_answers',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='cloze_options',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='cloze_text',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='drag_drop_mappings',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='drag_items',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='drop_zones',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_correct_mappings',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_drag_items',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_drop_zones',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='matching_correct_pairs',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='matching_left_items',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='matching_right_items',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_images',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='sequencing_correct_order',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='sequencing_items',
        ),
        migrations.AlterField(
            model_name='quizlesson',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('fill-blank', 'Fill in Blank')], default='multiple-choice', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('fill-blank', 'Fill in Blank'), ('short-answer', 'Short Answer')], default='multiple-choice', max_length=30),
        ),
    ]
