# Generated by Django 5.2.8 on 2025-11-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_remove_quizquestion_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocheckpointquiz',
            options={'ordering': ['timestamp_seconds', 'id'], 'verbose_name_plural': 'Video Check point Quiz'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='videocheckpointquiz',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='videocheckpointquiz',
            index=models.Index(fields=['lesson', 'timestamp_seconds'], name='courses_vid_lesson__b22dfd_idx'),
        ),
    ]
