# Generated by Django 5.2.8 on 2025-11-16 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_course_requires_final_assessment'),
    ]

    operations = [
        # Create EventType model
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'live_session')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'Live Session')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for frontend', max_length=50)),
                ('color', models.CharField(blank=True, help_text="Color code for UI (e.g., '#3B82F6')", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Event Types',
                'ordering': ['display_name'],
            },
        ),
        # Create Event model (create table in DB and add to state)
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
        ),
        # Add event_type field to Event (FK to EventType)
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='courses.eventtype'),
        ),
    ]
