# Generated by Django 5.2.8 on 2025-11-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_course_requires_final_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('live_session', 'Live Session'), ('deadline', 'Assignment Deadline'), ('qa_session', 'Student Q&A Session'), ('meeting', 'Course Review Meeting'), ('general', 'General Event')], default='general', max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
