# Generated by Django 5.2.8 on 2025-11-16 21:42

from django.db import migrations


def inspect_and_fix_event_table(apps, schema_editor):
    """Inspect Event table structure and fix event_type column issues"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Get table info
        cursor.execute("PRAGMA table_info(courses_event)")
        columns = {row[1]: {'type': row[2], 'notnull': row[3], 'default': row[4]} for row in cursor.fetchall()}
        
        # Check if old event_type CharField exists
        if 'event_type' in columns and 'event_type_id' in columns:
            # Both columns exist - we need to remove the old one
            # SQLite doesn't support DROP COLUMN, so we'll rename it
            try:
                cursor.execute("ALTER TABLE courses_event RENAME COLUMN event_type TO event_type_old")
            except Exception:
                # If rename fails, the column might not exist or already be renamed
                pass
        elif 'event_type' in columns and 'event_type_id' not in columns:
            # Only old column exists, rename it so Django can use event_type for the FK
            try:
                cursor.execute("ALTER TABLE courses_event RENAME COLUMN event_type TO event_type_old")
                # Now add the new event_type_id column
                cursor.execute("ALTER TABLE courses_event ADD COLUMN event_type_id INTEGER")
            except Exception as e:
                print(f"Error renaming column: {e}")
        elif 'event_type_id' not in columns:
            # event_type_id doesn't exist, add it
            cursor.execute("ALTER TABLE courses_event ADD COLUMN event_type_id INTEGER")


def reverse_fix(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_add_eventtype_and_event_field'),
    ]

    operations = [
        migrations.RunPython(
            inspect_and_fix_event_table,
            reverse_fix,
        ),
    ]
