# Generated by Django 5.2.8 on 2025-11-16 21:45

from django.db import migrations


def remove_old_event_type_column(apps, schema_editor):
    """Remove the old event_type_old column from Event table"""
    # SQLite doesn't support DROP COLUMN directly, so we'll recreate the table
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if event_type_old exists
        cursor.execute("PRAGMA table_info(courses_event)")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'event_type_old' in columns:
            # SQLite doesn't support DROP COLUMN in older versions
            # We'll use a workaround: create new table, copy data, drop old, rename new
            cursor.execute("""
                CREATE TABLE courses_event_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title varchar(255) NOT NULL,
                    description TEXT,
                    start_datetime datetime NOT NULL,
                    end_datetime datetime,
                    created_at datetime NOT NULL,
                    updated_at datetime NOT NULL,
                    course_id bigint,
                    event_type_id INTEGER
                )
            """)
            
            # Copy data (excluding event_type_old)
            cursor.execute("""
                INSERT INTO courses_event_new 
                (id, title, description, start_datetime, end_datetime, created_at, updated_at, course_id, event_type_id)
                SELECT id, title, description, start_datetime, end_datetime, created_at, updated_at, course_id, event_type_id
                FROM courses_event
            """)
            
            # Drop old table and rename new one
            cursor.execute("DROP TABLE courses_event")
            cursor.execute("ALTER TABLE courses_event_new RENAME TO courses_event")
            
            # Recreate indexes if needed
            cursor.execute("CREATE INDEX IF NOT EXISTS courses_event_course_id_idx ON courses_event(course_id)")
            cursor.execute("CREATE INDEX IF NOT EXISTS courses_event_event_type_id_idx ON courses_event(event_type_id)")


def reverse_remove(apps, schema_editor):
    """Reverse migration - not really reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_fix_event_type_nullable'),
    ]

    operations = [
        migrations.RunPython(
            remove_old_event_type_column,
            reverse_remove,
        ),
    ]

