# Generated by Django 5.2.8 on 2025-11-17 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0042_remove_old_event_type_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment_confirmed', 'Enrollment Confirmed'), ('enrollment_pending', 'Enrollment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('course_completed', 'Course Completed'), ('certificate_issued', 'Certificate Issued'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('assignment_graded', 'Assignment Graded'), ('quiz_graded', 'Quiz Graded'), ('course_announcement', 'Course Announcement'), ('lesson_unlocked', 'Lesson Unlocked'), ('module_unlocked', 'Module Unlocked'), ('general', 'General')], default='general', help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message/content')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the notification was last updated')),
                ('action_url', models.URLField(blank=True, help_text='Optional URL to navigate to when notification is clicked', max_length=500, null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for the notification (e.g., 'enrollment', 'payment', 'certificate')", max_length=100)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='courses_not_user_id_27e16c_idx'), models.Index(fields=['user', 'notification_type'], name='courses_not_user_id_d9def5_idx'), models.Index(fields=['-created_at'], name='courses_not_created_4780d2_idx')],
            },
        ),
    ]
