# Generated by Django 5.2.8 on 2025-11-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional: Associate with a specific course. If null, available for all courses by this teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Question Banks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('fill-blank', 'Fill in Blank'), ('short-answer', 'Short Answer')], default='multiple-choice', max_length=30)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_bank_questions/')),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points the question carries')),
                ('order', models.PositiveIntegerField(default=0)),
                ('blanks', models.JSONField(blank=True, default=list, help_text='List of correct answers for blanks. For multiple blanks, use list of strings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.questionbank')),
            ],
            options={
                'verbose_name_plural': 'Question Bank Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='question_bank_answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.questionbankquestion')),
            ],
            options={
                'verbose_name_plural': 'Question Bank Answers',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['teacher', '-created_at'], name='courses_que_teacher_d40bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['course', 'is_active'], name='courses_que_course__0722d3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankquestion',
            index=models.Index(fields=['question_bank', 'order'], name='courses_que_questio_dde4c6_idx'),
        ),
    ]
