# Generated by Django 5.2.8 on 2025-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_questionbank_questionbankquestion_questionbankanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='code_snippet',
            field=models.TextField(blank=True),
        ),
    ]
