# Generated by Django 5.2.8 on 2025-11-26 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_assignmentsubmission_code_snippet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlesson',
            name='late_deduction_max',
            field=models.FloatField(default=50.0, help_text='Maximum late deduction percentage'),
        ),
        migrations.AddField(
            model_name='assignmentlesson',
            name='late_deduction_per_day',
            field=models.FloatField(default=10.0, help_text='Percentage deducted per day late'),
        ),
        migrations.AddField(
            model_name='assignmentlesson',
            name='max_files',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of files a student can upload'),
        ),
        migrations.AddField(
            model_name='assignmentlesson',
            name='peer_review_enabled',
            field=models.BooleanField(default=False, help_text='Enable peer review for this assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Score after late deduction applied', null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='late_deduction_applied',
            field=models.FloatField(default=0.0, help_text='Percentage deducted for late submission'),
        ),
        migrations.AlterField(
            model_name='assignmentlesson',
            name='rubric_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of rubric criteria: [{"name": "...", "description": "...", "max_points": 10}, ...]'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_peer_review', 'Pending Peer Review'), ('peer_reviewed', 'Peer Reviewed'), ('graded', 'Graded'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment_submission_files/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.assignmentsubmission')),
            ],
            options={
                'verbose_name_plural': 'Assignment Submission Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_assignments', to='courses.lesson')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_to_do', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_assignments', to='courses.assignmentsubmission')),
            ],
            options={
                'verbose_name_plural': 'Peer Review Assignments',
            },
        ),
        migrations.CreateModel(
            name='PeerReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rubric_score', models.FloatField(default=0)),
                ('max_rubric_score', models.FloatField(default=0)),
                ('overall_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_summary', to='courses.assignmentsubmission')),
            ],
            options={
                'verbose_name_plural': 'Peer Review Summaries',
            },
        ),
        migrations.CreateModel(
            name='PeerRubricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=200)),
                ('criterion_description', models.TextField(blank=True)),
                ('max_points', models.FloatField(default=10)),
                ('points_awarded', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluations', to='courses.peerreviewassignment')),
            ],
            options={
                'verbose_name_plural': 'Peer Rubric Evaluations',
            },
        ),
        migrations.AddIndex(
            model_name='peerreviewassignment',
            index=models.Index(fields=['reviewer', 'is_completed'], name='courses_pee_reviewe_515dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='peerreviewassignment',
            index=models.Index(fields=['lesson', 'is_completed'], name='courses_pee_lesson__3ebc2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewassignment',
            unique_together={('submission', 'reviewer')},
        ),
    ]
