# Generated by Django 5.2.8 on 2025-11-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_assignmentlesson_late_deduction_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcourseassessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Maximum attempts allowed. 0 = unlimited attempts'),
        ),
    ]
