# Generated by Django 5.2.9 on 2025-12-14 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_finalcourseassessment_max_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='H5PContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parameters', models.JSONField(help_text='Content parameters from content/content.json')),
                ('metadata', models.JSONField(blank=True, help_text='Metadata from h5p.json', null=True)),
                ('content_path', models.CharField(blank=True, help_text='Path to content files on disk', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'H5P Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quizlesson',
            name='h5p_content',
            field=models.ForeignKey(blank=True, help_text='Optional H5P content for interactive quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_lessons', to='courses.h5pcontent'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='h5p_content',
            field=models.ForeignKey(blank=True, help_text='Optional H5P content for interactive video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_lessons', to='courses.h5pcontent'),
        ),
        migrations.CreateModel(
            name='H5PFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='h5p/content/%Y/%m/%d/')),
                ('original_path', models.CharField(blank=True, help_text='Original path in .h5p archive', max_length=500)),
                ('file_type', models.CharField(blank=True, help_text='File type (image, video, audio, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.h5pcontent')),
            ],
            options={
                'verbose_name_plural': 'H5P Files',
                'ordering': ['original_path'],
            },
        ),
        migrations.CreateModel(
            name='H5PLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Machine name (e.g., 'H5P.Quiz')", max_length=255)),
                ('title', models.CharField(help_text='Human-readable title', max_length=255)),
                ('major_version', models.IntegerField()),
                ('minor_version', models.IntegerField()),
                ('patch_version', models.IntegerField()),
                ('runnable', models.BooleanField(default=False, help_text='Whether this library can be used directly as content')),
                ('metadata_settings', models.JSONField(blank=True, help_text='Library metadata settings from library.json', null=True)),
                ('preloaded_js', models.JSONField(blank=True, default=list, help_text='List of JS files to preload')),
                ('preloaded_css', models.JSONField(blank=True, default=list, help_text='List of CSS files to preload')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of dependent libraries')),
                ('library_path', models.CharField(blank=True, help_text='Path to library files on disk', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'H5P Libraries',
                'indexes': [models.Index(fields=['name', 'major_version', 'minor_version'], name='courses_h5p_name_f6ed73_idx')],
                'unique_together': {('name', 'major_version', 'minor_version', 'patch_version')},
            },
        ),
        migrations.AddField(
            model_name='h5pcontent',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.h5plibrary'),
        ),
        migrations.CreateModel(
            name='H5PResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('opened', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now=True)),
                ('time', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('h5p_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.h5pcontent')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h5p_results', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h5p_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'H5P Results',
                'ordering': ['-finished'],
                'indexes': [models.Index(fields=['student', 'h5p_content'], name='courses_h5p_student_32bfcd_idx'), models.Index(fields=['student', 'lesson'], name='courses_h5p_student_92a068_idx')],
            },
        ),
    ]
