# Generated by Django 5.2.8 on 2025-11-27 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0047_alter_finalcourseassessment_max_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssessmentWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Weight of the final assessment in the final score calculation.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_weight', to='courses.finalcourseassessment')),
            ],
            options={
                'verbose_name': 'Final Assessment Weight',
                'verbose_name_plural': 'Final Assessment Weights',
            },
        ),
        migrations.CreateModel(
            name='GradingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_percentage', models.FloatField(default=60.0, help_text='Minimum total percentage required to pass the course.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_configuration', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LessonWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Weight of this lesson in the final score calculation.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_weight', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Weight',
                'verbose_name_plural': 'Lesson Weights',
            },
        ),
        migrations.CreateModel(
            name='StudentCourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weighted_score', models.FloatField(default=0.0)),
                ('total_possible_weighted_score', models.FloatField(default=0.0)),
                ('final_score_percentage', models.FloatField(default=0.0, help_text='Final calculated grade out of 100%')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='in_progress', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Course Grade',
                'verbose_name_plural': 'Student Course Grades',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentFinalAssessmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=100.0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('is_override', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='courses.finalcourseassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='StudentLessonGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=100.0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('is_override', models.BooleanField(default=False, help_text='If True, this score was manually set by a teacher.')),
                ('feedback', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'lesson'], name='grading_stu_student_09cc9a_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
